---
# yamllint disable rule:line-length
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  dependsOn:
    - name: minio
      namespace: default
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: thanos
      version: 11.4.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    query:
      enabled: true
      replicaCount: 2
      replicaLabels:
        - replica
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hostname: "thanos.${SECRET_DOMAIN}"
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "https://oauth.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://oauth.${SECRET_DOMAIN}/oauth2/start?rd=$scheme://$best_http_host$request_uri"
          # traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          # traefik.ingress.kubernetes.io/router.middlewares: networking-forward-auth@kubernetescrd
        tls: true
    queryFrontend:
      enabled: false
    bucketweb:
      enabled: true
    compactor:
      enabled: true
      strategyType: Recreate
      persistence:
        size: 30Gi
    storegateway:
      enabled: true
    ruler:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    objstoreConfig: |-
      type: s3
      config:
        bucket: thanos
        endpoint: "s3.${SECRET_DOMAIN}"
        access_key: "${SECRET_MINIO_ROOT_USER}"
        secret_key: "${SECRET_MINIO_ROOT_PASSWORD}"
        insecure: false

  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Ingress
              name: thanos-query
            patch:
              - op: add
                path: /spec/ingressClassName
                value: nginx
